DECLARE @PRODUTO VARCHAR(50) = '148149 - BISC BANA AVEIA CANELA NESFIT 160G'; -- coloque o código do produto aqui

SELECT 
    @PRODUTO AS PRODUTO,
    SUM(DISTINCT VLR_RECEITA_BRUTA) AS RECEITA_BRUTA
FROM [4_TMP].REL_CHATBOT
WHERE PRODUTO = @PRODUTO;