SELECT 
    CONVERT(date, CONVERT(varchar(8), SK_TEMPO), 112) AS DATA,
    SUM(VLR_RECEITA_BRUTA) AS SOMA_RECEITA_BRUTA,
    SUM(VLR_LUCRO_BRUTO) AS SOMA_LUCRO_BRUTO,
    SUM(QTD_ITEM_CUPOM) AS SOMA_QTD_CUPOM
FROM [4_TMP].REL_CHATBOT
WHERE SK_TEMPO = CONVERT(varchar(8), GETDATE(), 112)  -- filtra o dia atual
GROUP BY CONVERT(date, CONVERT(varchar(8), SK_TEMPO), 112)

-- Receita bruta de um dia específico
DECLARE @DATA_ALVO DATE = '2025-09-01'; -- coloque a data desejada
SELECT 
    CONVERT(date, CONVERT(varchar(8), SK_TEMPO), 112) AS DATA,
    SUM(VLR_RECEITA_BRUTA) AS SOMA_RECEITA_BRUTA,
    SUM(VLR_LUCRO_BRUTO) AS SOMA_LUCRO_BRUTO,
    SUM(QTD_ITEM_CUPOM) AS SOMA_QTD_CUPOM
FROM [4_TMP].REL_CHATBOT
WHERE SK_TEMPO = CONVERT(varchar(8), @DATA_ALVO, 112) 
GROUP BY CONVERT(date, CONVERT(varchar(8), SK_TEMPO), 112);