WITH VENDAS_MENSAL AS (
    SELECT
        YEAR(CONVERT(date, CONVERT(varchar(8), SK_TEMPO), 112)) AS ANO,
        MONTH(CONVERT(date, CONVERT(varchar(8), SK_TEMPO), 112)) AS MES,
        SUM(VLR_RECEITA_BRUTA) AS RECEITA_BRUTA
    FROM [4_TMP].REL_CHATBOT
    GROUP BY YEAR(CONVERT(date, CONVERT(varchar(8), SK_TEMPO), 112)),
             MONTH(CONVERT(date, CONVERT(varchar(8), SK_TEMPO), 112))
)
SELECT 
    v1.ANO,
    v1.MES,
    v1.RECEITA_BRUTA AS RECEITA_ATUAL,
    v2.RECEITA_BRUTA AS RECEITA_MES_PASSADO,
    v3.RECEITA_BRUTA AS RECEITA_MES_ANO_PASSADO,
    (v1.RECEITA_BRUTA - v2.RECEITA_BRUTA) AS DIFERENCA_MES_PASSADO,
    (v1.RECEITA_BRUTA - v3.RECEITA_BRUTA) AS DIFERENCA_ANO_PASSADO
FROM VENDAS_MENSAL v1
LEFT JOIN VENDAS_MENSAL v2 
    ON v2.ANO = CASE WHEN v1.MES = 1 THEN v1.ANO - 1 ELSE v1.ANO END
   AND v2.MES = CASE WHEN v1.MES = 1 THEN 12 ELSE v1.MES - 1 END
LEFT JOIN VENDAS_MENSAL v3 
    ON v3.ANO = v1.ANO - 1 
   AND v3.MES = v1.MES
WHERE v1.ANO = YEAR(GETDATE())
  AND v1.MES = MONTH(GETDATE());  -- filtra só o mês atual