WITH VENDAS_DIA AS (
    SELECT
        CONVERT(date, CONVERT(varchar(8), SK_TEMPO), 112) AS DATA,
        SUM(VLR_RECEITA_BRUTA) AS RECEITA_BRUTA
    FROM [4_TMP].REL_CHATBOT
    GROUP BY CONVERT(date, CONVERT(varchar(8), SK_TEMPO), 112)
)
SELECT 
    v1.DATA AS DATA_ATUAL,
    v1.RECEITA_BRUTA AS RECEITA_ATUAL,
    v2.DATA AS DATA_ANO_PASSADO,
    v2.RECEITA_BRUTA AS RECEITA_ANO_PASSADO,
    (v1.RECEITA_BRUTA - v2.RECEITA_BRUTA) AS DIFERENCA_ABS,
    ( (v1.RECEITA_BRUTA - v2.RECEITA_BRUTA) * 100.0 / NULLIF(v2.RECEITA_BRUTA,0) ) AS DIFERENCA_PCT
FROM VENDAS_DIA v1
LEFT JOIN VENDAS_DIA v2 
    ON DATEPART(WEEKDAY, v1.DATA) = DATEPART(WEEKDAY, v2.DATA)
   AND v2.DATA = DATEADD(YEAR, -1, v1.DATA)
WHERE v1.DATA = DATEADD(DAY, -1, CAST(GETDATE() AS DATE));