select top 1
NOM_DEPARTAMENTO,
NOM_SECAO,
NOM_CATEGORIA,
NOM_SUBCATEGORIA,
PRODUTO,
    SUM(VLR_RECEITA_LIQUIDA) AS VENDAS
from [4_TMP].REL_CHATBOT
group by 
NOM_DEPARTAMENTO,
NOM_SECAO,
NOM_CATEGORIA,
NOM_SUBCATEGORIA,
PRODUTO
order by VENDAS;